name: doctordiagnose
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  dio: ^5.4.1
  envied: ^0.5.3
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  google_generative_ai: ^0.2.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  envied_generator: ^0.5.3

flutter:
  uses-material-design: true
  assets:
    - assets/avatars/
