// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARO_t4f5HFLaVTu7mT889sRGwHSDB-xgw',
    appId: '1:726713077680:web:28eafe659d4c3564715075',
    messagingSenderId: '726713077680',
    projectId: 'dodiagnose',
    authDomain: 'dodiagnose.firebaseapp.com',
    storageBucket: 'dodiagnose.appspot.com',
    measurementId: 'G-MGK4DSTT6Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3p8jOIw7lF_8pKJXB4WT2vkoZU5K8arM',
    appId: '1:726713077680:android:477e5d1c4e335cc7715075',
    messagingSenderId: '726713077680',
    projectId: 'dodiagnose',
    storageBucket: 'dodiagnose.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCypaCv0xHTmWuUvqrcGqeulCsRhOlnvOU',
    appId: '1:726713077680:ios:c54e4b47e1afa923715075',
    messagingSenderId: '726713077680',
    projectId: 'dodiagnose',
    storageBucket: 'dodiagnose.appspot.com',
    iosBundleId: 'com.aditya.doctordiagnose',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCypaCv0xHTmWuUvqrcGqeulCsRhOlnvOU',
    appId: '1:726713077680:ios:ac101357f97f7610715075',
    messagingSenderId: '726713077680',
    projectId: 'dodiagnose',
    storageBucket: 'dodiagnose.appspot.com',
    iosBundleId: 'com.aditya.doctordiagnose.RunnerTests',
  );
}
